### ISSUE TITLE
Consider "consumer version" instead of "version"?

### ISSUE THREAD

**Issue by bethesque** [Babylonpartners/pact-broker-client#2]
One of the problems that has emerged from the names I used for the parameters in the URL `/provider/FOO/consumer/BAR/version/1.0.0` is that it's not clear that the "version" is the consumer application version, not the "version" of the pact. I'm trying to go through all the client code and update it to make this clearer. Would you consider changing "version" to "consumer-version"?

**Comment by mbeltre** [comment]
This is a good idea, I'll make those changes.

**Comment by bethesque** [comment]
👍
